image: node:8

before_script:
  - npm install

cache:
  paths:
    - node_modules/
test:lint:
  script:
    - npm run lint
test:node:8:
  script:
    - npm install -g codecov
    - npm test && codecov -t $codecov_token
test:node:6:
  image: node:6
  script:
    - npm test
test:node:7:
  image: node:7
  script:
    - npm test